# Generated by Django 5.1.5 on 2025-02-01 16:19

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='course_images/internship_demo.jpg', upload_to='course_images/'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('college', models.CharField(max_length=250)),
                ('year', models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')])),
                ('ieeMember', models.BooleanField()),
                ('ieeId', models.CharField(blank=True, max_length=100, null=True)),
                ('isReferralId', models.BooleanField()),
                ('referralCode', models.CharField(max_length=100)),
                ('interestInStudingAboard', models.IntegerField(choices=[(1, 'Yes'), (2, 'No'), (3, 'Maybe')])),
                ('InterestedIn', models.IntegerField(choices=[(1, 'Programming'), (2, 'Designing'), (3, 'Non Coding'), (4, 'Hardware'), (5, 'None of the above')])),
                ('bill', models.CharField(max_length=100)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
            ],
        ),
    ]
