# Generated by Django 5.1.5 on 2025-03-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_course_image_course_price_alter_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='referralCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
